import { supabase } from '../lib/supabaseClient';
import Head from 'next/head'
import Layout from '../components/layout'
import { useUser } from "@supabase/auth-helpers-react";
// Simon
import Form from "./form.js";
import { useState } from "react";
import FormModal from "@/components/FormModal";


export async function getServerSideProps() {
  let { data } = await supabase.from("beers").select();

  return {
    props: {
      beers: data,
    },
  };
}

export default function Home({beers}) {
  const [openModal, setOpenModal] = useState(false);
  const userSession = useUser();

  return (
    <Layout>
      <Head>
        <title>GazeEDIfication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </Head>
      <main>
      <button onClick={() => setOpenModal(!openModal)}>
          Entrer une consommation
        </button>
        <FormModal isOpen={openModal} onClose={() => setOpenModal(false)}>
          <FormModal.Header>Nouvelle consommation</FormModal.Header>
          <FormModal.Body>
            {/* Modal Body */}
            <Form />
          </FormModal.Body>
          <FormModal.Footer>
            <FormModal.DismissButton className="modal-button-close">
              Annuler
            </FormModal.DismissButton>
            <button className="modal-button-save">Sauvegarder</button>
          </FormModal.Footer>
        </FormModal>
      <div className="container">
          {userSession ? <div>Hello {userSession.id} </div> : null}
          <ul>
            {beers.map((beer) => (
              <li key={beer.id}>{beer.name}</li>
            ))}
          </ul>
          <button onClick={() => console.log(userSession)}>test</button>
        </div>

      </main>
    </Layout>
  )
}
